env:
  node: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  no-bitwise: error
  eqeqeq: error
  guard-for-in: error
  no-extend-native: error
  no-use-before-define:
    - error
    - functions: false
  no-caller: error
  no-sequences: error
  no-irregular-whitespace: error
  no-new: error
  require-jsdoc:
    - error
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
  strict:
    - error
    - function
  no-undef: error
  no-unused-vars: error
  indent:
    - 2
    - 2
    - SwitchCase: 1
  one-var:
    - 2
    - never
  valid-jsdoc: error
