env:
  node: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  no-bitwise: 2
  eqeqeq: 2
  guard-for-in: 2
  no-extend-native: 2
  no-use-before-define:
    - 2
    - functions: false
  no-caller: 2
  no-sequences: 2
  no-irregular-whitespace: 2
  no-new: 2
  require-jsdoc:
    - error
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
  strict:
    - 2
    - function
  no-undef: 2
  no-unused-vars: 2
  indent:
    - 2
    - 2
    - SwitchCase: 1
  one-var:
    - 2
    - never
  valid-jsdoc: error
